<?if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED !== true) die();?>
<?include(GetLangFileName(dirname(__FILE__)."/", "/payment.php"));
CModule::IncludeModule("sale");
require_once 'Mobilpay/Payment/Request/Abstract.php';
require_once 'Mobilpay/Payment/Request/Card.php';
require_once 'Mobilpay/Payment/Recurrence.php';
require_once 'Mobilpay/Payment/Invoice.php';
require_once 'Mobilpay/Payment/Address.php';
$signature = CSalePaySystemAction::GetParamValue("signature");
$certPath =  CSalePaySystemAction::GetParamValue("certPath");
$inv_id = IntVal($GLOBALS["SALE_INPUT_PARAMS"]["ORDER"]["ID"]);
$inv_number = $GLOBALS["SALE_INPUT_PARAMS"]["ORDER"]["ACCOUNT_NUMBER"];
$out_summ = number_format(floatval(CSalePaySystemAction::GetParamValue("SHOULD_PAY")), 2, ".", "");
$isTest = trim(CSalePaySystemAction::GetParamValue("IS_TEST"));
$type = CSalePaySystemAction::GetParamValue("type");
?>

<?if(strlen($isTest) > 0):
	
	$paymentUrl = 'http://sandboxsecure.mobilpay.ro';
else:
	
	$paymentUrl = 'https://secure.mobilpay.ro';
endif;
$x509FilePath 	= $_SERVER["DOCUMENT_ROOT"]."/bitrix/php_interface/include/sale_payment/mobilpay/live.1EKY-8K1D-2858-J6J2-HY57.public.cer";
?>
<?
try
{
	srand((double) microtime() * 1000000);
	$objPmReqCard 						= new Mobilpay_Payment_Request_Card();
	#merchant account signature - generated by mobilpay.ro for every merchant account
	#semnatura contului de comerciant - mergi pe www.mobilpay.ro Admin -> Conturi de comerciant -> Detalii -> Setari securitate
	$objPmReqCard->signature 			=  $signature;
	#you should assign here the transaction ID registered by your application for this commercial operation
	#order_id should be unique for a merchant account
	$objPmReqCard->orderId 				= $inv_id;
	#supply return_url and/or confirm_url only if you want to overwrite the ones configured for the service/product when it was created
	#if you don't want to supply a different return/confirm URL, just let it null
	$objPmReqCard->confirmUrl 			= 'http://www.luxoft-training.ro/order/mobilpay_recieve.php'; 
	$objPmReqCard->returnUrl 			= 'http://www.luxoft-training.ro/order/order/?filter_status=F&filter_history=Y'; 

	$objPmReqCard->recurrence = new Mobilpay_Payment_Recurrence();
	$objPmReqCard->recurrence->payments_no = 'X';
	$objPmReqCard->recurrence->interval_day = 'YY';

	#detalii cu privire la plata: moneda, suma, descrierea
	#payment details: currency, amount, description
	$objPmReqCard->invoice = new Mobilpay_Payment_Invoice();
	$objPmReqCard->invoice->currency	= 'RON';
	$objPmReqCard->invoice->amount		= $out_summ;
	$objPmReqCard->invoice->details		= 'Payment for order '.$inv_id;
	
	#detalii cu privire la adresa posesorului cardului
	#details on the cardholder address
	$billingAddress 				= new Mobilpay_Payment_Address();
	$billingAddress->type			= CSalePaySystemAction::GetParamValue("type");
	$billingAddress->firstName		= CSalePaySystemAction::GetParamValue("firstName");
	$billingAddress->lastName		= CSalePaySystemAction::GetParamValue("lastName");
	$billingAddress->fiscalNumber	= CSalePaySystemAction::GetParamValue("fiscalNumber");;
	$billingAddress->identityNumber	= CSalePaySystemAction::GetParamValue("identityNumber");;
	$billingAddress->country		= CSalePaySystemAction::GetParamValue("country");;
	$billingAddress->county			= CSalePaySystemAction::GetParamValue("county");;
	$billingAddress->city			= CSalePaySystemAction::GetParamValue("city");;
	$billingAddress->zipCode		= CSalePaySystemAction::GetParamValue("zip_code");;
	$billingAddress->address		= CSalePaySystemAction::GetParamValue("address");;
	$billingAddress->email			= CSalePaySystemAction::GetParamValue("email");;
	$billingAddress->mobilePhone	= CSalePaySystemAction::GetParamValue("mobilePhone");;
	$billingAddress->bank			= CSalePaySystemAction::GetParamValue("bank");;
	$billingAddress->iban			= CSalePaySystemAction::GetParamValue("iban");;
	$objPmReqCard->invoice->setBillingAddress($billingAddress);
	
	#detalii cu privire la adresa de livrare
	#details on the shipping address
	$shippingAddress 				= new Mobilpay_Payment_Address();
	$shippingAddress->type			= $_POST['shipping_type'];
	$shippingAddress->firstName		= $_POST['shipping_first_name'];
	$shippingAddress->lastName		= $_POST['shipping_last_name'];
	$shippingAddress->fiscalNumber	= $_POST['shipping_fiscal_number'];
	$shippingAddress->identityNumber= $_POST['shipping_identity_number'];
	$shippingAddress->country		= $_POST['shipping_country'];
	$shippingAddress->county		= $_POST['shipping_county'];
	$shippingAddress->city			= $_POST['shipping_city'];
	$shippingAddress->zipCode		= $_POST['shipping_zip_code'];
	$shippingAddress->address		= $_POST['shipping_address'];
	$shippingAddress->email			= $_POST['shipping_email'];
	$shippingAddress->mobilePhone	= $_POST['shipping_mobile_phone'];
	$shippingAddress->bank			= $_POST['shipping_bank'];
	$shippingAddress->iban			= $_POST['shipping_iban'];
	$objPmReqCard->invoice->setShippingAddress($shippingAddress);
	//print_r($objPmReqCard);
	$objPmReqCard->encrypt($x509FilePath);
}
catch(Exception $e)
{
}
?>
<div class="span-15 prepend-1">
<h3></h3>
<?php if(!($e instanceof Exception)):?>
<p>
	<form name="frmPaymentRedirect" method="post" action="<?php echo $paymentUrl;?>">
	<input type="hidden" name="env_key" value="<?php echo $objPmReqCard->getEnvKey();?>"/>
	<input type="hidden" name="data" value="<?php echo $objPmReqCard->getEncData();?>"/>
	<p>
		Pentru a finaliza plata vei redirectat catre pagina de plati securizata a mobilpay.ro
	</p>
	<p>
		<input type="submit" name="submit" class="btn btn-primary" value="Redirectionat"/>
	</p>
	</form>
</p>
<!-- <script type="text/javascript" language="javascript">
	window.setTimeout(document.frmPaymentRedirect.submit(), 5000);
</script> -->
<?php else:?>
<p><strong><?php echo $e->getMessage();?></strong></p>
<?php endif;?>