<?
/* ID IBLOCK BELOW: */
define("D_TIMETABLE_ID_IBLOCK", 9);
define("D_EXPERT_ID_IBLOCK", 56);
define("D_TIMETABLECLASSES_ID_IBLOCK", 10);
define("D_COURSE_ID_IBLOCK", 6);
define("D_RECORDS_IBLOCK", 64);
define("D_CITIES_IBLOCK", 51);
define("D_SEMINARS_IBLOCK", 7);
define("D_ELEMENTSUBSCRIBE_IBLOCK", 75);
define("D_NEWCATALOG_IBLOCK", 76);
define("D_TEMPCATALOG_IBLOCK", 90);
define("D_TEMPCATALOG_DIRECTIONS_IBLOCK", 94);
define("D_CATALOG_COMPLEX_IBLOCK", 49);

define("D_SEMINARS_REFERENCE", 73);
define("D_NEWS", 23);
define("D_PARTNERS", 58);
define("D_CLIENTS_REFERENCE", 63);
define("D_CLIENTS_FEEDBACK", 61);
define("D_EXPERTS_ANSWERS", 85);
define("D_HISTORY_CALENDAR", 86);

define("D_EN_EXPERT_ID_IBLOCK", 98);
define("D_EN_COURSE_ID_IBLOCK", 97);
define("D_EN_CATALOG_IBLOCK", 100);
define("D_EN_SCHEDULE_IBLOCK", 99);
define("D_EN_LOCATIONS_IBLOCK", 95);


/*USER GROUPS*/
define("GROUP_FORBID_EXPERTS_IBLOCK_EDIT", 53);
define("GROUP_FORBID_EDU_SECTION", 57);
define("GROUP_STORE_TESTER", 83);
define("EN_GROUP_NOTIFICATIONS_ABOUT_APPLICATIONS", 74);

/*ID PROPS */
define("CITY_PROP_ID", 50);
define("DURATION_PROP_ID", 57);
define("DISCOUNT_PROP_ID", 539);

/* ID CITIES BELOW: */
define("CITY_ID_ONLINE", 14909);
define("CITY_ID_OMSK", 5742);
define("CITY_ID_MOSCOW", 5741);
define("CITY_ID_KIEV", 5745);
define("CITY_ID_DNEPR", 5747);
define("CITY_ID_ODESSA", 5746);
define("CITY_ID_SPB", 5744);
define("CITY_ID_MINSK", 28042);
define("CITY_ID_NOVOROSSIYSK", 33125);
define("CITY_ID_NOVOSIBIRSK", 9190);

define("CITY_IS_SITEACTIVE", 129);

/* ID PAYMENT_TYPES LUX TR BELOW: */

define("PAYMENT_TYPE_ID_LUX_INDIVIDUAL", 1);
define("PAYMENT_TYPE_ID_LUX_LEGAL_ENTITY", 3);
define("PAYMENT_TYPE_ID_SL_INDIVIDUAL", 2);
define("PAYMENT_TYPE_ID_SL_LEGAL_ENTITY", 4);

define("PAYMENT_SYSTEM_ID_LUX_ONLINE", 1);
define("PAYMENT_SYSTEM_ID_SL_ONLINE", 2);
define("PAYMENT_SYSTEM_ID_LUX_OFERTA_LEGAL", 3);
define("PAYMENT_SYSTEM_ID_LUX_KVITANCIYA", 4);
define("PAYMENT_SYSTEM_ID_SL_KVITANCIYA", 5);
define("PAYMENT_SYSTEM_ID_SL_OFERTA_LEGAL", 6);


define("D_DIFF_ELEMENT_PRIVATEMAN", 22985);
define("ENUM_SEND_INFO_ANSWER", 142);
define("ENUM_IS_NOT_IN_CATALOG", 143);

/*EMAIL TEMPLATES IDs*/
define("T_EMAIL_QUESTIONS_TO_LTR", 102);
define("T_EMAIL_QUESTIONS_TO_AUTHOR", 103);


define("T_EN_SIMPLE_NOTICATION_ABOUT_EVENT_APPLICATIONS", 126);
define("T_EN_NOTICATION_ABOUT_EVENT_SPECIFIC_DATE", 125);

define("T_EN_SIMPLE_USER_NOTIFICATION_ABOUT_EVENT_APPLICATIONS",132);
define("T_EN_USER_NOTICATION_ABOUT_EVENT_SPECIFIC_DATE", 133);

define("CITY_CURRENCY_RUB", 63);
define("CITY_CURRENCY_BYR", 147);
define("CITY_CURRENCY_GRN", 64);


/*Forms*/
define("EN_ENTRIES_COURSES_AND_EVENTS", 11);

?>